name: Maven Central Deploy

# Trigger this action when a release is published, or on a manual trigger (testing).
on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  deploy-to-maven-central:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    # The private key used to sign releases is checked in encrypted
    #   then decrypted on the fly to be used to sign artefacts.
    - name: Decrypt the artefact signing key
      run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.ANDROID_SONATYPE_PRIVATE_KEY_DECRYPT_PASSWORD }}" --output secrets/private.key secrets/private.key.gpg

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # This can often be used as a testing ground
    - name: Deploy to Maven Central io.github.aniketsk (Sonatype)
      run: ./gradlew clean publishToSonatype -PhmsSdkGroup="io.github.aniketsk" -PHMS_ANDROID_SDK_COMMON_VERSION_NAME="${{github.ref_name}}" -PossrhPassword="${{ secrets.ANDROID_SONATYPE_PASSWORD}}" -Psigning.password="${{ secrets.ANDROID_SONATYPE_PRIVATE_KEY_SIGNING_PASSWORD }}"

    # The final release to your domain name
    - name: Deploy to Maven Central com.aniketkadam.pdb (Sonatype)
      run: ./gradlew clean publishToSonatype -PhmsSdkGroup="com.aniketkadam.pdb" -PHMS_ANDROID_SDK_COMMON_VERSION_NAME="${{github.ref_name}}" -PossrhPassword="${{ secrets.ANDROID_SONATYPE_PASSWORD}}" -Psigning.password="${{ secrets.ANDROID_SONATYPE_PRIVATE_KEY_SIGNING_PASSWORD }}"
